### ISSUE TITLE
FA missions: Timed expansion alwyas on

### ISSUE THREAD

**Issue by Katharsas** [FAForever/faf-coop-maps#362] opened 2021-01-20 11:50 UTC
From many forum reports i gathered that the timed expansion setting is alwyas turned on regardless of what option you select for the FA missions.

**Comment by speed2CZ** [comment] 2021-04-23 10:22
First FA missions works as intended, when off, it doesnt expand.

**Comment by Katharsas** [comment] 2021-04-25 05:59
Yeah same for last FA mission. Dont know which missions had the problem.

**Comment by JBStokley** [comment] 2022-07-22 22:40
Did some digging on this one and I'm pretty sure it's a bug. `ScenarioInfo.Options.Expansion` is treated like a bool in the custom missions, but when looking at the original game missions it is treated as a string with a literal value of either "true" or "false".

https://github.com/FAForever/faf-coop-maps/blob/cae22113679fc82486fa602c54d740b410e39141/FAF_Coop_Operation_Blockade/FAF_Coop_Operation_Blockade_script.lua#L29

vs.

https://github.com/FAForever/faf-coop-maps/blob/cfbdf50f149f56c6795a3df5fc933be7bc1010ff/X1CA_Coop_001/X1CA_Coop_001_script.lua#L217


Because it's a string value it will always pass the test used to set the timer triggers, like this.
https://github.com/FAForever/faf-coop-maps/blob/cae22113679fc82486fa602c54d740b410e39141/FAF_Coop_Operation_Blockade/FAF_Coop_Operation_Blockade_script.lua#L213-L216


Affected missions are:
[Operation Yath Aez](https://github.com/FAForever/faf-coop-maps/blob/370c3d6e43f0f5e359a691fc2b74c883fa5b6793/FAF_Coop_Operation_Yath_Aez/FAF_Coop_Operation_Yath_Aez_script.lua)
[Operation Blockade](https://github.com/FAForever/faf-coop-maps/blob/370c3d6e43f0f5e359a691fc2b74c883fa5b6793/FAF_Coop_Operation_Blockade/FAF_Coop_Operation_Blockade_script.lua)
[Operation Uhthe Thuum QAI](https://github.com/FAForever/faf-coop-maps/blob/370c3d6e43f0f5e359a691fc2b74c883fa5b6793/FAF_Coop_Operation_Uhthe_Thuum_QAI/FAF_Coop_Operation_Uhthe_Thuum_QAI_script.lua)
[Operation Holy Raid](https://github.com/FAForever/faf-coop-maps/blob/b1160f595508928472ef691ea6773c8c2189ad79/FAF_Coop_Operation_Holy_Raid/FAF_Coop_Operation_Holy_Raid_script.lua)
[Operation Ioz Shavoh Kael](https://github.com/FAForever/faf-coop-maps/blob/370c3d6e43f0f5e359a691fc2b74c883fa5b6793/FAF_Coop_Operation_Ioz_Shavoh_Kael/FAF_Coop_Operation_Ioz_Shavoh_Kael_script.lua)
[Operation Golden Crystals](https://github.com/FAForever/faf-coop-maps/blob/30ebd5adba4666e26ed4f786ea1ce5422ee2b648/FAF_Coop_Operation_Golden_Crystals/FAF_Coop_Operation_Golden_Crystals_script.lua)
[Fort Clarke Assault](https://github.com/FAForever/faf-coop-maps/blob/cfbdf50f149f56c6795a3df5fc933be7bc1010ff/FAF_Coop_Fort_Clarke_Assault/FAF_Coop_Fort_Clarke_Assault_script.lua)
[Operation Tha Atha Aez](https://github.com/FAForever/faf-coop-maps/blob/30ebd5adba4666e26ed4f786ea1ce5422ee2b648/FAF_Coop_Operation_Tha_Atha_Aez/FAF_Coop_Operation_Tha_Atha_Aez_script.lua)

**Comment by Katharsas** [comment] 2022-07-25 23:09
@UnassumingKiwi Nice! Do you know about the Coop Discord?
Not sure but I think the Sera missions get copied to here from the Beta versions made over there. Might want to make sure that your change does not disappear when the next Sera mission update is copied (?) over.

**Comment by UnassumingKiwi** [comment] 2022-07-29 18:58
@Katharsas I'm not familiar with that Discord, I'm on the main FAF discord tho. How can I find the Coop Discord?

**Comment by Uveso** [comment] 2022-07-30 12:47
@UnassumingKiwi 

if you are on the FAF discord; look into the `information-resources` channel, there are all discord server listed.

coop discord:
https://discord.gg/ayzAVr9JUV

**Comment by speed2CZ** [comment] 2022-11-26 16:27
This should be fixed now

**Closed by speed2CZ** 2022-11-26 16:27 UTC
