### ISSUE TITLE
Cybran M2: All HQ in Eastern Aeon 

### ISSUE THREAD

**Issue by TheKeyBlue** [FAForever/faf-coop-maps#140] opened 2016-09-16 22:01 UTC
The aeon base in the east still has 3 HQs. Not sure if this is desired or not.

**Comment by speed2CZ** [comment] 2016-09-17 06:38
Only few FA missions got changed to use support factories so far. Duplicate of https://github.com/FAForever/faf-coop-maps/issues/61

**Closed by speed2CZ** 2016-09-17 06:38 UTC
