### ISSUE TITLE
FA1 Desync

### ISSUE THREAD

**Issue by MattDeering** [FAForever/faf-coop-maps#15] opened 2015-05-19 03:38 UTC
Played with Invisible, desynced around when we got T3

http://pastebin.com/Kii4Eacj

**Comment by aeoncleanse** [comment] 2015-05-21 20:28
It's possible this is not a bug related to coop and you just... desynced. It happens. See if it happens every time, in the same spot.

**Comment by speed2CZ** [comment] 2015-09-13 21:47
is the desync still hapenning? didnt see any other report on it

**Comment by speed2CZ** [comment] 2016-03-01 21:28
Didn't get any more report about desyncing, so closing

**Closed by speed2CZ** 2016-03-01 21:28 UTC
Labels: help wanted
